{{- $fullName := include "grafana.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ include "grafana.password" . }}
  {{- end }}
