apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.gke.name }}
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: {{ .Values.storageClass.gke.type }}
  fstype: {{ .Values.storageClass.gke.fsType }}
  replication-type: none